#! /bin/sh

sxhkd &
picom &
mopidy &

bspc monitor -d 1 2 3 4 5

bspc config border_width          3
bspc config window_gap            40

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config focused_border_color  "#929be5"
bspc config normal_border_color   "#282C34"

bspc rule -a Zathura state=tiled

$HOME/.scripts/polybarlaunch.sh &
