#! /bin/sh

sxhkd &
picom &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          100

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.scripts/polybarlaunch.sh &
