# Aliases
alias ls='ls -Fh --color=auto'
alias rm='rm -i'
alias grep='grep --color=auto'
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias ll='ls -altr'
alias szp='source ~/.config/zsh/.zshrc'
alias ezp='nvim ~/.config/zsh/.zshrc'
alias eni='nvim ~/.config/nvim/init.lua'
alias fd='fdfind'
